# Generated by Django 2.0 on 2019-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='date_delete',
        ),
        migrations.AddField(
            model_name='doctor',
            name='login',
            field=models.CharField(default=1, max_length=20, verbose_name='Логин:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default=1, max_length=20, verbose_name='Пароль:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='info',
            field=models.CharField(max_length=10000, verbose_name='Информация о враче'),
        ),
    ]
