# Generated by Django 2.0 on 2019-12-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191217_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='polis',
            field=models.CharField(default=1, max_length=100, verbose_name='Полис пациента '),
            preserve_default=False,
        ),
    ]
